import type { PkaEntry, PkaCategory } from "@/components/pka-game/types";

export const PKA_DATA: PkaEntry[] = [
  // ─── BASIC (Evans pKa table) ────────────────────────────────────────────────

  // Strong mineral/halogen acids
  {
    id: "hi",
    name: "Hydroiodic acid",
    functionalGroup: "Hydroiodic acid",
    smiles: "[H:1]I",
    pka: -10,
    pkaDisplay: "−10",
    categories: ["mineral"],
    source: "basic",
    note: "Strongest of the common hydrohalic acids",
  },
  {
    id: "hbr",
    name: "Hydrobromic acid",
    functionalGroup: "Hydrobromic acid",
    smiles: "[H:1]Br",
    pka: -9,
    pkaDisplay: "−9",
    categories: ["mineral"],
    source: "basic",
  },
  {
    id: "hcl",
    name: "Hydrochloric acid",
    functionalGroup: "Hydrochloric acid",
    smiles: "[H:1]Cl",
    pka: -6,
    pkaDisplay: "−6",
    categories: ["mineral"],
    source: "basic",
  },
  {
    id: "h2so4",
    name: "Sulfuric acid",
    functionalGroup: "Sulfuric acid",
    smiles: "[H:1]OS(=O)(=O)O",
    pka: -3,
    pkaDisplay: "−3",
    categories: ["mineral"],
    source: "basic",
    note: "First ionisation; second ionisation pKa ~1.99",
  },
  {
    id: "h3o",
    name: "Hydronium ion",
    functionalGroup: "Hydronium ion",
    smiles: "[H:1][OH2+]",
    pka: -1.7,
    pkaDisplay: "−1.7",
    categories: ["mineral"],
    source: "basic",
  },
  {
    id: "tosic",
    name: "p-Toluenesulfonic acid (tosic acid)",
    functionalGroup: "Sulfonic acid",
    smiles: "[H:1]OS(=O)(=O)c1ccc(C)cc1",
    pka: -1,
    pkaDisplay: "−1",
    categories: ["mineral"],
    source: "basic",
    note: "Common sulfonic acid used in organic synthesis",
  },
  {
    id: "hf",
    name: "Hydrofluoric acid",
    functionalGroup: "Hydrofluoric acid",
    smiles: "[H:1]F",
    pka: 3.2,
    pkaDisplay: "3.2",
    categories: ["mineral", "oxygen"],
    source: "basic",
    note: "Weak acid despite F being the most electronegative element; strong H-bonding",
  },

  // O–H acids
  {
    id: "acetic",
    name: "Acetic acid",
    functionalGroup: "Carboxylic acid",
    smiles: "[H:1]OC(=O)C",
    pka: 4,
    pkaDisplay: "~4",
    categories: ["oxygen"],
    source: "basic",
    note: "Resonance-stabilised conjugate base (acetate)",
  },
  {
    id: "water",
    name: "Water",
    functionalGroup: "Water",
    smiles: "[H:1]O[H]",
    pka: 14,
    pkaDisplay: "14",
    categories: ["oxygen"],
    source: "basic",
  },
  {
    id: "methanol",
    name: "Methanol",
    functionalGroup: "Alcohol",
    smiles: "[H:1]OC",
    pka: 17,
    pkaDisplay: "~17",
    categories: ["oxygen"],
    source: "basic",
    note: "Alkoxide conjugate base",
  },

  // N–H / S–H acids
  {
    id: "ammonium",
    name: "Ammonium ion",
    functionalGroup: "Protonated amine",
    smiles: "[H:1][NH3+]",
    pka: 10,
    pkaDisplay: "9–11",
    categories: ["nitrogen"],
    source: "basic",
    note: "pKa varies with substitution; primary alkylammonium ~10–11",
  },
  {
    id: "methanethiol",
    name: "Methanethiol",
    functionalGroup: "Thiol",
    smiles: "[H:1]SC",
    pka: 13,
    pkaDisplay: "~13",
    categories: ["sulfur"],
    source: "basic",
    note: "More acidic than alcohols; thiolate is a better nucleophile than alkoxide",
  },

  // Active methylene
  {
    id: "malonate",
    name: "Dimethyl malonate",
    functionalGroup: "Malonate",
    smiles: "[H:1][CH](C(=O)OC)C(=O)OC",
    pka: 13,
    pkaDisplay: "~13",
    categories: ["carbon"],
    source: "basic",
    note: "1,3-dicarbonyl stabilises carbanion by resonance",
  },

  // C–H acids
  {
    id: "acetone-ch",
    name: "Acetone (α C–H)",
    functionalGroup: "Ketone",
    smiles: "[H:1][CH2]C(C)=O",
    pka: 20,
    pkaDisplay: "20–24",
    categories: ["carbon"],
    source: "basic",
    note: "Enolate stabilised by carbonyl resonance",
  },
  {
    id: "acetonitrile-ch",
    name: "Acetonitrile (α C–H)",
    functionalGroup: "Nitrile",
    smiles: "[H:1][CH2]C#N",
    pka: 25,
    pkaDisplay: "~25",
    categories: ["carbon"],
    source: "basic",
    note: "Cyano group stabilises α-carbanion inductively",
  },
  {
    id: "methyl-acetate-ch",
    name: "Methyl acetate (α C–H)",
    functionalGroup: "Ester",
    smiles: "[H:1][CH2]C(=O)OC",
    pka: 25,
    pkaDisplay: "~25",
    categories: ["carbon"],
    source: "basic",
    note: "Less acidic than ketone alpha-H due to lone pair donation from OR",
  },
  {
    id: "propyne",
    name: "Propyne (terminal alkyne)",
    functionalGroup: "Alkyne",
    smiles: "[H:1]C#CC",
    pka: 25,
    pkaDisplay: "~25",
    categories: ["carbon"],
    source: "basic",
    note: "sp C–H; high s-character bond increases acidity",
  },
  {
    id: "dmso-ch",
    name: "Dimethylsulfoxide (α C–H)",
    functionalGroup: "Sulfoxide",
    smiles: "[H:1][CH2]S(=O)C",
    pka: 31,
    pkaDisplay: "~31",
    categories: ["carbon", "sulfur"],
    source: "basic",
    note: "Used as base in combination with NaH (Corey–Chaykovsky)",
  },
  {
    id: "ammonia",
    name: "Ammonia",
    functionalGroup: "Amine",
    smiles: "[H:1]N([H])[H]",
    pka: 35,
    pkaDisplay: "~35",
    categories: ["nitrogen"],
    source: "basic",
  },
  {
    id: "hydrogen",
    name: "Dihydrogen",
    functionalGroup: "Hydrogen",
    smiles: "[H:1][H]",
    pka: 36,
    pkaDisplay: "36",
    categories: ["other"],
    source: "basic",
  },
  {
    id: "propene-ch",
    name: "Propene (vinylic C–H)",
    functionalGroup: "Alkene",
    smiles: "[H:1]C=CC",
    pka: 43,
    pkaDisplay: "~43",
    categories: ["carbon"],
    source: "basic",
    note: "sp² C–H; higher s-character than sp³ but less than alkyne",
  },
  {
    id: "propane-ch",
    name: "Propane (C–H)",
    functionalGroup: "Alkane",
    smiles: "[H:1]CCC",
    pka: 50,
    pkaDisplay: "~50",
    categories: ["carbon"],
    source: "basic",
    note: "Least acidic functional group; requires very strong bases (BuLi, LDA)",
  },

  // ─── ADVANCED (Evans extended + Hans Reich) ──────────────────────────────────

  {
    id: "tfa",
    name: "Trifluoroacetic acid",
    functionalGroup: "Carboxylic acid",
    smiles: "[H:1]OC(=O)C(F)(F)F",
    pka: 0,
    pkaDisplay: "~0",
    categories: ["oxygen"],
    source: "advanced",
    note: "Three F atoms strongly withdraw electron density, greatly enhancing acidity",
  },
  {
    id: "dichloroacetic",
    name: "Dichloroacetic acid",
    functionalGroup: "Carboxylic acid",
    smiles: "[H:1]OC(=O)C(Cl)Cl",
    pka: 1.5,
    pkaDisplay: "~1.5",
    categories: ["oxygen"],
    source: "advanced",
  },
  {
    id: "chloroacetic",
    name: "Chloroacetic acid",
    functionalGroup: "Carboxylic acid",
    smiles: "[H:1]OC(=O)CCl",
    pka: 2.9,
    pkaDisplay: "~2.9",
    categories: ["oxygen"],
    source: "advanced",
  },
  {
    id: "formic",
    name: "Formic acid",
    functionalGroup: "Carboxylic acid",
    smiles: "[H:1]OC=O",
    pka: 3.75,
    pkaDisplay: "~3.75",
    categories: ["oxygen"],
    source: "advanced",
  },
  {
    id: "benzoic",
    name: "Benzoic acid",
    functionalGroup: "Carboxylic acid",
    smiles: "[H:1]OC(=O)c1ccccc1",
    pka: 4.2,
    pkaDisplay: "~4.2",
    categories: ["oxygen"],
    source: "advanced",
  },
  {
    id: "pyridinium",
    name: "Pyridinium ion",
    functionalGroup: "Protonated amine",
    smiles: "[H:1][n+]1ccccc1",
    pka: 5.3,
    pkaDisplay: "~5.3",
    categories: ["nitrogen"],
    source: "advanced",
    note: "N lone pair delocalised into ring; much weaker base than alkylamines",
  },
  {
    id: "p-nitrophenol",
    name: "4-Nitrophenol",
    functionalGroup: "Phenol",
    smiles: "[H:1]Oc1ccc([N+](=O)[O-])cc1",
    pka: 7.1,
    pkaDisplay: "~7.1",
    categories: ["oxygen"],
    source: "advanced",
    note: "Nitro group withdraws electrons, strongly increasing phenol acidity",
  },
  {
    id: "imidazolium",
    name: "Imidazolium ion",
    functionalGroup: "Protonated amine",
    smiles: "[H:1][n+]1ccnc1",
    pka: 7,
    pkaDisplay: "~7",
    categories: ["nitrogen"],
    source: "advanced",
    note: "Physiologically relevant; NHC precursor",
  },
  {
    id: "acetylacetone",
    name: "Acetylacetone (2,4-pentanedione)",
    functionalGroup: "1,3-Diketone",
    smiles: "[H:1][CH](C(C)=O)C(C)=O",
    pka: 9,
    pkaDisplay: "~9",
    categories: ["carbon"],
    source: "advanced",
    note: "Two flanking carbonyls give exceptional C–H acidity",
  },
  {
    id: "phenol",
    name: "Phenol",
    functionalGroup: "Phenol",
    smiles: "[H:1]Oc1ccccc1",
    pka: 10,
    pkaDisplay: "~10",
    categories: ["oxygen"],
    source: "advanced",
    note: "Phenoxide stabilised by resonance into ring",
  },
  {
    id: "t-butylammonium",
    name: "tert-Butylammonium",
    functionalGroup: "Protonated amine",
    smiles: "[H:1][NH3+]C(C)(C)C",
    pka: 10.7,
    pkaDisplay: "~10.7",
    categories: ["nitrogen"],
    source: "advanced",
  },
  {
    id: "dipah",
    name: "Diisopropylamine (DIPAH⁺)",
    functionalGroup: "Protonated amine",
    smiles: "[H:1][NH2+](C(C)C)C(C)C",
    pka: 11.4,
    pkaDisplay: "~11.4",
    categories: ["nitrogen"],
    source: "advanced",
    note: "Conjugate acid of LDA; a widely used non-nucleophilic base",
  },
  {
    id: "malononitrile",
    name: "Malononitrile",
    functionalGroup: "Malonate",
    smiles: "[H:1][CH](C#N)C#N",
    pka: 11,
    pkaDisplay: "~11",
    categories: ["carbon"],
    source: "advanced",
    note: "Two cyano groups provide exceptional stabilisation",
  },
  {
    id: "ethyl-acetoacetate",
    name: "Ethyl acetoacetate",
    functionalGroup: "β-Ketoester",
    smiles: "[H:1][CH](CC(=O)OCC)C(C)=O",
    pka: 11,
    pkaDisplay: "~11",
    categories: ["carbon"],
    source: "advanced",
    note: "Classic active methylene compound",
  },
  {
    id: "diethyl-malonate",
    name: "Diethyl malonate",
    functionalGroup: "Malonate",
    smiles: "[H:1][CH](C(=O)OCC)C(=O)OCC",
    pka: 13,
    pkaDisplay: "~13",
    categories: ["carbon"],
    source: "advanced",
  },
  {
    id: "cyclopentadiene",
    name: "Cyclopentadiene",
    functionalGroup: "Cyclopentadiene",
    smiles: "[H:1]C1C=CC=C1",
    pka: 16,
    pkaDisplay: "~16",
    categories: ["carbon"],
    source: "advanced",
    note: "Aromatic cyclopentadienyl anion; only 4 C–H acids are in this class",
  },
  {
    id: "t-butanol",
    name: "tert-Butanol",
    functionalGroup: "Alcohol",
    smiles: "[H:1]OC(C)(C)C",
    pka: 19,
    pkaDisplay: "~19",
    categories: ["oxygen"],
    source: "advanced",
    note: "Slightly more basic than methanol due to electron-donating alkyl groups",
  },
  {
    id: "nitromethane",
    name: "Nitromethane (α C–H)",
    functionalGroup: "Nitroalkane",
    smiles: "[H:1][CH2][N+](=O)[O-]",
    pka: 17,
    pkaDisplay: "~17",
    categories: ["carbon"],
    source: "advanced",
    note: "Nitronate anion; used in Henry reaction",
  },
  {
    id: "indene",
    name: "Indene",
    functionalGroup: "Indene",
    smiles: "[H:1]C1C=Cc2ccccc21",
    pka: 20,
    pkaDisplay: "~20",
    categories: ["carbon"],
    source: "advanced",
    note: "Aromatic indene anion (partial aromatic stabilisation)",
  },
  {
    id: "cyclohexanone-ch",
    name: "Cyclohexanone (α C–H)",
    functionalGroup: "Ketone",
    smiles: "[H:1][C@@H]1CCCCC1=O",
    pka: 20,
    pkaDisplay: "~20",
    categories: ["carbon"],
    source: "advanced",
  },
  {
    id: "fluorene",
    name: "Fluorene (C9–H)",
    functionalGroup: "Fluorene",
    smiles: "[H:1]C1c2ccccc2Cc2ccccc21",
    pka: 23,
    pkaDisplay: "~23",
    categories: ["carbon"],
    source: "advanced",
    note: "Fluorenyl anion has aromatic (14π) character",
  },
  {
    id: "chloroform",
    name: "Chloroform",
    functionalGroup: "Haloalkane",
    smiles: "[H:1]C(Cl)(Cl)Cl",
    pka: 24,
    pkaDisplay: "~24",
    categories: ["carbon"],
    source: "advanced",
    note: "Three halogens destabilise only slightly via induction; pKa in DMSO",
  },
  {
    id: "acetylene",
    name: "Acetylene",
    functionalGroup: "Alkyne",
    smiles: "[H:1]C#C[H]",
    pka: 25,
    pkaDisplay: "~25",
    categories: ["carbon"],
    source: "advanced",
    note: "Parent terminal alkyne; sp C–H",
  },
  {
    id: "propionitrile-ch",
    name: "Propionitrile (α C–H)",
    functionalGroup: "Nitrile",
    smiles: "[H:1][CH2]C(CC)#N",
    pka: 25,
    pkaDisplay: "~25",
    categories: ["carbon"],
    source: "advanced",
  },
  {
    id: "dimethyl-sulfone-ch",
    name: "Dimethyl sulfone (α C–H)",
    functionalGroup: "Sulfone",
    smiles: "[H:1][CH2]S(=O)(=O)C",
    pka: 31,
    pkaDisplay: "~31",
    categories: ["carbon", "sulfur"],
    source: "advanced",
  },
  {
    id: "triphenylmethane",
    name: "Triphenylmethane",
    functionalGroup: "Triarylmethane",
    smiles: "[H:1]C(c1ccccc1)(c1ccccc1)c1ccccc1",
    pka: 31,
    pkaDisplay: "~31",
    categories: ["carbon"],
    source: "advanced",
    note: "Trityl carbanion stabilised by delocalisation into three phenyl rings",
  },
  {
    id: "aniline-conj",
    name: "Anilinium ion",
    functionalGroup: "Protonated amine",
    smiles: "[H:1][NH3+]c1ccccc1",
    pka: 4.6,
    pkaDisplay: "~4.6",
    categories: ["nitrogen"],
    source: "advanced",
    note: "Ring lone pair donation makes aniline a much weaker base than alkylamines",
  },
];

export const CATEGORIES: { id: PkaCategory; label: string; description: string }[] = [
  { id: "mineral",  label: "Mineral / Halogen acids", description: "HI, HBr, HCl, H₂SO₄, H₃O⁺, HF, tosic acid" },
  { id: "oxygen",   label: "O–H acids",               description: "Carboxylic acids, water, alcohols, phenols" },
  { id: "nitrogen", label: "N–H acids",               description: "Amines, protonated amines, pyridinium" },
  { id: "sulfur",   label: "S–H acids",               description: "Thiols, sulfoxides, sulfones" },
  { id: "carbon",   label: "C–H acids",               description: "Ketones, esters, nitriles, alkynes, alkenes, alkanes" },
  { id: "other",    label: "Other",                   description: "H₂ and miscellaneous" },
];

export function getPool(difficulty: "basic" | "advanced", categories: PkaCategory[]): PkaEntry[] {
  return PKA_DATA.filter((e) => {
    const diffOk = difficulty === "advanced" || e.source === "basic";
    const catOk = e.categories.some((c) => categories.includes(c));
    return diffOk && catOk;
  });
}

export function shuffled<T>(arr: T[]): T[] {
  const out = [...arr];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}
